server:
  port: 8080

spring:
  application:
    name: Kinpustan
  datasource:
    url: jdbc:h2:mem:kinpustan_db
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console

# Configuración SpringDoc OpenAPI (Swagger)
springdoc:
  api-docs:
    path: /v3/api-docs  # Endpoint para el JSON de la API
    enabled: true
  swagger-ui:
    path: /swagger-ui.html  # Interfaz gráfica
    enabled: true
    tags-sorter: alpha
    operations-sorter: alpha
  show-actuator: true
  cache:
    disabled: true  # Desactiva cache en desarrollo

# Configuración de logging para diagnóstico
logging:
  level:
    org.springdoc: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE